version: '3.8'

services:
  app:
    build: .
    environment:
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PORT: ${PORT}
    # NO especificamos ports aquí, Railway los asigna