[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "java -jar app.jar"

[healthcheck]
path = "/"
timeout = "30s"
interval = "15s"
retries = 3

[restart]
policy = "on_failure"
max_retries = 3