#Es la configuración especifica para railway,
#sirve para poder desplegarlo en su plataforma.

[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
[deploy]

[database]

[healthcheck]
path = "/health"
timeout = "30s"
interval = "15s"
retries = 3

[restart]
policy = "on_failure"
max_retries = 3